[build]
command = "python manage.py collectstatic --noinput && python manage.py migrate"
Starting Container
[2025-10-06 16:58:37 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2025-10-06 16:58:37 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2025-10-06 16:58:37 +0000] [1] [INFO] Using worker: sync
[2025-10-06 16:58:37 +0000] [2] [INFO] Booting worker with pid: 2
/app/.venv/lib/python3.11/site-packages/django/core/handlers/base.py:61: UserWarning: No directory at: /app/staticfiles/
  mw_instance = middleware(adapted_handler)